import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  trackerSidebar: [
    {
      type: 'category',
      label: 'Status Tracker',
      collapsed: false,
      items: [
        {type: 'doc', id: 'intro', label: 'Overview'},
        {
          type: 'category',
          label: 'Countries',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'tracker'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Editorial',
      collapsed: false,
      items: ['methodology', 'contribute', 'changelog', 'about'],
    },
  ],
  lspSidebar: [
    {
      type: 'category',
      label: 'Large Scale Pilots',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'lsp'}],
    },
  ],
};

export default sidebars;
